# Generated by Django 3.2 on 2022-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, unique=True)),
                ('qc_plot', models.BooleanField(verbose_name='qc_plot')),
                ('dropkick', models.BooleanField(verbose_name='dropkick')),
                ('default', models.BooleanField(verbose_name='default')),
                ('custom', models.BooleanField(verbose_name='custom')),
                ('csv_bool', models.BooleanField(default=False)),
                ('h5ad_bool', models.BooleanField(default=False)),
                ('tsv_bool', models.BooleanField(default=False)),
                ('min_genes', models.IntegerField(blank=True, default='50', null=True, verbose_name='min_genes')),
                ('mito_names', models.CharField(blank=True, default='^mt-|^MT-', max_length=100, null=True, verbose_name='mito_names')),
                ('n_ambient', models.IntegerField(blank=True, default='10', null=True, verbose_name='n_ambient')),
                ('n_hvgs', models.IntegerField(blank=True, default='2000', null=True, verbose_name='n_hvgs')),
                ('metrics', models.CharField(blank=True, default='arcsinh_n_genes_by_counts', max_length=100, null=True, verbose_name='metrics')),
                ('thresh_methods', models.CharField(blank=True, choices=[('multiotsu', 'multiotsu'), ('otsu', 'otsu'), ('li', 'li'), ('mean', 'mean')], default='multiotsu', max_length=10, null=True, verbose_name='thresh_methods')),
                ('directions', models.CharField(blank=True, choices=[('above', 'above'), ('below', 'below')], default='above', max_length=10, null=True, verbose_name='directions')),
                ('alphas', models.CharField(blank=True, default='0.1', max_length=10, null=True, verbose_name='alphas')),
                ('max_iter', models.IntegerField(blank=True, default='2000', null=True, verbose_name='max_iter')),
                ('n_jobs', models.IntegerField(blank=True, default='5', null=True, verbose_name='n_jobs')),
                ('seed', models.IntegerField(blank=True, default='18', null=True, verbose_name='seed')),
                ('score_thresh', models.DecimalField(blank=True, decimal_places=5, default=0.5, error_messages={'required': 'Please enter a value between 0 and 1.'}, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter file output name.', max_length=500, verbose_name='file name')),
                ('upload', models.FileField(help_text='Only H5AD files are supported.', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
            ],
            options={
                'verbose_name': 'file',
                'ordering': ['uploaded_at', 'name'],
            },
        ),
    ]
