# Generated by Django 3.2 on 2022-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customparam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
