# Generated by Django 3.2 on 2022-02-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0002_alter_customparam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customparam',
            name='name',
            field=models.CharField(default='sample', max_length=50),
        ),
    ]
