# Generated by Django 3.2 on 2022-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0003_customparam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customparam',
            name='score_thresh',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.5, error_messages={'required': 'Please enter a value between 0 and 1.'}, max_digits=3, null=True),
        ),
    ]
