# Generated by Django 3.2 on 2022-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(error_messages={'blank': 'Comments field is required.', 'null': 'Comments field is required.'}),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email field is required.', 'null': 'Email field is required.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is required.', 'null': 'Name field is required.'}, max_length=50),
        ),
    ]
