# Generated by Django 3.2 on 2022-03-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0009_auto_20220323_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
